### ISSUE TITLE
可以移植1.12.2吗

### ISSUE THREAD

**Issue by 1zyao** [CSneko/Better_end_rod#1]

**Comment by 1zyao** [comment]
https://github.com/1zyao/Better_end_rod 1.12.2forge的移植

**Comment by CSneko** [comment]
当然可以

**Comment by CSneko** [comment]
[一个可能遇到的问题]后面的更新很有可能(约为99%)会使用[ctLib](https://github.com/CSneko/ctLib)作为前置,但ctLib最低要求在java11运行（尽管它支持低版本Forge），然而低版本Forge貌似只能在java8运行

**Comment by 1zyao** [comment]
ctLib干嘛的 加前缀还是啥

**Comment by CSneko** [comment]
作用很杂，但是存储数据要用

**Comment by 1zyao** [comment]
https://www.mcmod.cn/class/9689.html这个玩意能让1.12.2用java17跑起来
