### ISSUE TITLE
插入多个？

### ISSUE THREAD

**Issue by 1zyao** [CSneko/Better_end_rod#2]
新建一个状态 控制速度 速度是按照插入的几根计算 每多一个就多乘一遍0.5

**Comment by CSneko** [comment]
好主意，明天试试[doge]

**Comment by maoyvna** [comment]
我连使用都没有整明白，拖到mods里面进游戏不识别

**Comment by CSneko** [comment]
@maoyvna _不识别大概率是使用了错误的加载器，要运行这个模组必须使用Fabric/Quilt，它不支持Forge
